<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include=".env" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UpWard.Application\Upward.Application.csproj" />
    <ProjectReference Include="..\Upward.Infrastructure\Upward.Infrastructure.csproj" />
    <ProjectReference Include="..\Upward.Shared\Upward.Shared.csproj" />
  </ItemGroup>

</Project>
