<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.19" />
    <PackageReference Include="Stripe.net" Version="52.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Upward.Domain\Upward.Domain.csproj" />
    <ProjectReference Include="..\Upward.Shared\Upward.Shared.csproj" />
  </ItemGroup>

</Project>
